# Generated by Django 5.1.5 on 2026-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("HERO", "Hero Section (Top 3)"),
                            ("COLLAGE", "Image Collage"),
                            ("RESEARCH_STRIP", "Research Strip"),
                            ("REFLECTIONS", "Reflections/Essays"),
                            ("QNA", "Q&A Section"),
                            ("FEATURED_MEDIA", "Featured Podcasts/Videos"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Section heading (e.g., "Editor\'s Picks", "Deep Dive")',
                        max_length=200,
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Order on homepage (lower = higher)"
                    ),
                ),
                (
                    "manually_curated",
                    models.BooleanField(
                        default=True,
                        help_text="If False, content will be auto-populated based on rules",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this section on homepage"
                    ),
                ),
                (
                    "auto_content_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECENT", "Most Recent"),
                            ("POPULAR", "Most Viewed"),
                            ("EDITOR_PICKS", "Editor Picks"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auto_article_count",
                    models.PositiveIntegerField(
                        default=5, help_text="Number of articles to auto-populate"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="homepage_sections",
                        to="content.article",
                    ),
                ),
                (
                    "podcasts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="homepage_sections",
                        to="content.podcast",
                    ),
                ),
                (
                    "videos",
                    models.ManyToManyField(
                        blank=True, related_name="homepage_sections", to="content.video"
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Section",
                "verbose_name_plural": "Homepage Sections",
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["position", "is_active"],
                        name="homepage_ho_positio_ce73b5_idx",
                    )
                ],
            },
        ),
    ]
