# Generated by Django 5.1.5 on 2026-02-13 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=400)),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary for listing pages and SEO",
                        max_length=500,
                    ),
                ),
                ("body", models.TextField(help_text="Main article content")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/heroes/%Y/%m/"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("NEWS", "News"),
                            ("RESEARCH", "Research"),
                            ("ESSAY", "Essay"),
                        ],
                        db_index=True,
                        default="NEWS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "is_editor_pick",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Featured on homepage"
                    ),
                ),
                (
                    "is_paywalled",
                    models.BooleanField(
                        default=False,
                        help_text="Requires authentication to read full content",
                    ),
                ),
                (
                    "sources_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sources cited"
                    ),
                ),
                (
                    "experts_interviewed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of experts interviewed"
                    ),
                ),
                (
                    "confidence_rating",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Confidence"),
                            ("MEDIUM", "Medium Confidence"),
                            ("LOW", "Low Confidence"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "what_we_dont_know",
                    models.TextField(
                        blank=True,
                        help_text="Transparency about unknowns and limitations",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("Article", "Article"),
                            ("NewsArticle", "News Article"),
                            ("FAQ", "FAQ"),
                            ("HowTo", "How-To"),
                        ],
                        default="Article",
                        max_length=20,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                ("description", models.TextField()),
                (
                    "audio_file",
                    models.FileField(
                        help_text="MP3 or other audio format",
                        upload_to="podcasts/%Y/%m/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="podcasts/thumbnails/%Y/%m/"
                    ),
                ),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, help_text="Full transcript of the podcast"
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                ("description", models.TextField()),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload video file (MP4 recommended)",
                        null=True,
                        upload_to="videos/%Y/%m/",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, help_text="YouTube or Vimeo URL"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbnails/%Y/%m/"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-published_at"],
            },
        ),
    ]
