# Generated by Django 5.1.5 on 2026-02-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
